#!/usr/bin/env python

import os
import sys
import inspect

import click

parentdir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, parentdir)
print(sys.path)

from site_scan import ScanConfig
from site_scan import SiteScanner

@click.command()
@click.option('--ports', default='80,443', help='comma separated list of possible web ports')
@click.option('--target-hosts', prompt='Which hosts would you like to scan (comma separated)', help='the comma-separated list of target hosts')
def scan(ports, target_hosts):
    """Scan doer"""
    print("I will scan {} ports on hosts: {}".format(ports, target_hosts))

    config = ScanConfig()
    config.add_text_hosts(target_hosts)
    config.add_text_ports(ports)

    scanner = SiteScanner(config)

    results = scanner.scan()

if __name__ == '__main__':
    scan()
